### ISSUE TITLE
RRA checklist

### ISSUE THREAD

**Issue by mjzffr** [mozilla/wpt-sync#42]
Possibly relevant subset of https://wiki.mozilla.org/Security/FirefoxOperations#Security_Checklist

Infrastructure
--------------

* [x] Access and application logs must be archived for a minimum of 90 days

* (n/a) If service has an admin panels, it must:
  * only be available behind Mozilla VPN (which provides MFA)
  * require Auth0 authentication

Development
-----------
* [ ] Sign all release tags, and ideally commits as well
  * Developers should [configure git to sign all tags](http://micropipes.com/blog//2016/08/31/signing-your-commits-on-github-with-a-gpg-key/) and upload their PGP fingerprint to https://login.mozilla.com
  * The signature verification will eventually become a requirement to shipping a release to staging & prod: the tag being deployed in the pipeline must have a matching tag in git signed by a project owner. This control is designed to reduce the risk of a 3rd party GitHub integration from compromising our source code.
* [x] **Keep 3rd-party libraries up to date**
  * For Python applications, enable pyup security updates:
    * Add a pyup config to your repo (example config: https://github.com/mozilla-services/antenna/blob/master/.pyup.yml)
    * From the "add a team" dropdown for your repo add the relevant "Approved Mozilla PyUp Configuration" team for your github org (e.g. for [mozilla](https://github.com/orgs/mozilla/teams/approved-mozilla-pyup-configuration) and [mozilla-services](https://github.com/orgs/mozilla-services/teams/approved-mozilla-pyup-configuration)) and grant it write permission.
    * Notify secops@mozilla.com to enable the integration in pyup
    * Consider using ``pip list --outdated`` or [requires.io](https://requires.io/) too
* [x] **Integrate static code analysis in CI**, and avoid merging code with issues
    * Python applications should use [Bandit](https://github.com/openstack/bandit)
    * Use whitelisting mechanisms in these tools to deal with false positives

Logging
-------
* [ ] Publish detailed logs in [mozlog](https://github.com/mozilla-services/Dockerflow/blob/master/docs/mozlog.md) format (**APP-MOZLOG**)
  * Business logic must be logged with app specific codes (see [FxA](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#defined-errors))
  * Access control failures must be logged at WARN level
